sky:
  mysql:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 512218
  redis:
    host: localhost
    port: 6379
    database: 0