server:
  port: 8080

spring:
  application:
    name: sky-take-out
  profiles:
    active: dev
#  main:
#    allow-circular-references: true
  datasource:
    driver-class-name: ${sky.mysql.driver-class-name}
    url: jdbc:mysql://${sky.mysql.host}:${sky.mysql.port}/${sky.mysql.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${sky.mysql.username}
    password: ${sky.mysql.password}
  data:
    redis:
      host: ${sky.redis.host}
      port: ${sky.redis.port}
      database: ${sky.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启控制台打印
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: cqu-take-out-saomamiyaochangdubugou
    # 设置jwt过期时间，2小时*1000
    admin-ttl: 7200000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: cqu-take-out-user-saomamiyaochangdubugou
    user-ttl: 7200000000
    user-token-name: authentication
  aliyunoss:
    endpoint: ${sky.aliyunoss.endpoint}
    bucketName: ${sky.aliyunoss.bucketName}
    region: ${sky.aliyunoss.region}
  wechat:
    appid: ${appid}
    secret: ${secret}