sky:
  mysql:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 512218
  redis:
    host: localhost
    port: 6379
    database: 1
  aliyunoss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: dogeggly
    region: cn-beijing
  wechat:
    appid: wx4f1d6ff8c2fc37f3
    secret: 3121a7efd1929052e440c656398a4b81